### ISSUE TITLE
can not change registry!!! why?

### ISSUE THREAD

**Issue by monkey-sking** [shadowsocks/shadowsocks-csharp#105]
windows 7  sp1 64bit

**Comment by clowwindy** [comment]
Update to 2.1.6, click start on boot, then check the logs.

**Comment by monkey-sking** [comment]
这是我点击启用代理弹出的窗口：

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.IOException: 没有可用的数据了。

   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.GetValueNames()
   在 Shadowsocks.Controller.SystemProxy.CopyProxySettingFromLan()
   在 Shadowsocks.Controller.SystemProxy.Enable(Boolean global)
   在 Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   在 Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)
   在 Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
Shadowsocks
    程序集版本: 2.1.6.0
    Win32 版本: 2.1.6.0
    基本代码: file:///C:/Users/runking/Dropbox/ss/Shadowsocks.exe
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5468 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。


下面是日志内容：
Shadowsocks started
Shadowsocks started
System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 106.185.32.109:52084
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 106.185.32.109:52084
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)

**Comment by clowwindy** [comment]
暂时无法重现。

**Comment by monkey-sking** [comment]
我使用了云端，是不是根这个有关系？

**Comment by iKirby** [comment]
闲的蛋疼啊，用云端。。。

**Comment by monkey-sking** [comment]
这个程序没有在云端里面，
我只是在想可能与云端有关系。

**Comment by iKirby** [comment]
这...不明。

**Comment by dofine** [comment]
今天妹子的电脑上也遇到了这个问题。无法启用。

**Comment by monkey-sking** [comment]
https://plus.google.com/108327028069953436875/posts/ThKZ7ncrNrL
看下这个。貌似是权限的问题，等加班完后，我回家在电脑上试试。
