### ISSUE TITLE
多谢作者，请问可以出一个不带polipo转http代理的版本吗？

### ISSUE THREAD

**Issue by chaizia** [shadowsocks/shadowsocks-csharp#108]
转了很大一圈，最后还是回到作者这里来了
看到更新十分好用，只是我一直使用firefox，不需要polipo.exe来转换sock5到http
请问作者可以出一个不带polipo转换的精简版本吗？
多谢作者。

**Comment by clowwindy** [comment]
没有精力维护多个版本。

**Comment by chaizia** [comment]
：）多谢解答。准备尝试自己动手试试，多谢
