### ISSUE TITLE
win7 (64bit)使用最新版不稳定

### ISSUE THREAD

**Issue by tvvocold** [shadowsocks/shadowsocks-csharp#110]
一直是 服务器连接被重置 ，偶尔能翻出去
1, 服务器一样，在Linux客户机上使用确没问题。
2, DNS一样，都是8.8.8.8

**Comment by clowwindy** [comment]
无法重现，请提供更多信息以便重现这个问题。

**Comment by tvvocold** [comment]
Shadowsocks started
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)Shadowsocks started
System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 212.47.229.210:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 212.47.229.210:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 ip:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 ip:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)

**Comment by clowwindy** [comment]
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

这种问题就别来提 issue 了。原因都很明显了，网络问题。

**Comment by tvvocold** [comment]
但是在linux下没问题，同样网络

**Comment by clowwindy** [comment]
自己用一些网络工具查查呗，我又没时间登到你电脑上帮你查。
