### ISSUE TITLE
Share over LAN doesn't work

### ISSUE THREAD

**Issue by Provissy** [shadowsocks/shadowsocks-csharp#111]
So ... This issue is simple.
OS: Windows 7 64 bit.
Issue: Share over LAN function doesn't work.
and PS: Can you change the license to the MIT?

**Comment by clowwindy** [comment]
Define "doesn't work"

http://www.mediawiki.org/wiki/How_to_report_a_bug

**Comment by Provissy** [comment]
![qq 20150105210241](https://cloud.githubusercontent.com/assets/9506924/5612830/7881e3f6-951e-11e4-85b1-68fdf13a98bf.png)


![qq 20150105210255](https://cloud.githubusercontent.com/assets/9506924/5612833/84ca48ec-951e-11e4-98d5-9c89a38194f9.png)

嗯。。。就是不工作，没人成功过。。。
话说这功能是这么使用的吧。。？打开后不需要为浏览器设置代理即可走代理。
如果不是那么很抱歉打搅了。

**Comment by clowwindy** [comment]
不能。启用后只是监听局域网地址。因为没有时间请自行搜索这个功能怎么使用。
