### ISSUE TITLE
然后再来一个Issue，关于polipo

### ISSUE THREAD

**Issue by Provissy** [shadowsocks/shadowsocks-csharp#112]
一个就是polipo会崩溃，这是别人反馈的。
还有一个是会弹出来命令行，写着貌似是变量名不可用，也是别人反馈的，一时找不到截图。
总的来说SS C#的问题非常多，望尽快修复，SS是个很不错的工程，在此表示感激。
最后再次问下，能否将许可协议修改为MIT？
谢谢。

**Comment by clowwindy** [comment]
1. 无法重现，请提供更多信息以便重现
2. 无法重现，请提供更多信息以便重现
3. 不能，不欢迎闭源分支
