### ISSUE TITLE
Can not start the application without administrator privilege in WIN 7.

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-csharp#114]
测试环境1 WIN 7 64 BIT，必须使用管理员权限才能正常打开程序。

<2.1.6版本，非管理员权限，打开程序，右下角不显示程序托盘，进程存在。
=2.1.6版本，非管理员权限，打开程序，右下角托盘显示，但是右键点击无反应。

测试环境2 WIN 8.1 64BIT,使用或者不使用管理员权限打开都正常（2.1.6还没有测）

**Comment by clowwindy** [comment]
谁能重现这个问题或者有兴趣到楼主机器上调试一下？

**Comment by myliyifei** [comment]
没有看到有出错的日志。程序设计本身需要管理员权限么
2015年1月6日 下午3:56于 "clowwindy" <notifications@github.com>写道：

**Comment by clowwindy** [comment]
不需要，除非装了 360 之类的奇葩软件。

**Comment by myliyifei** [comment]
没有装，我重装了一遍系统，还是不行，估计可能跟什么软件冲突了吧，百思不得其解。要是有更详细的日志就好了。

2015-01-11 22:23 GMT+08:00 clowwindy <notifications@github.com>:

**Comment by bombless** [comment]
哈，可以试试QQ远程调试看看情况，就看楼主愿不愿意了。
这种问题我相信日志启到的作用有限，而且反正软件都启动不了，日志能不能写出来都是个问题。

**Comment by myliyifei** [comment]
可以啊，我邮箱myliyifei@gmail.com

在 2015年1月17日 下午4:15，York Xiang <notifications@github.com>写道：

**Comment by myliyifei** [comment]
今天试了一下，又莫名其妙的可以了。。。哎，不能重现故障，先关了吧。

在 2015年1月17日 下午6:42，Li Yi-Fei <myliyifei@gmail.com>写道：
