### ISSUE TITLE
Support GFWList

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-csharp#115]
希望Win版能跟进自动更新gfwlist功能

**Comment by clowwindy** [comment]
谁有兴趣实现这个功能可以发个 pull request。

**Comment by dwbclz** [comment]
谢谢C大！
自从用上了新版 shadowsocks-csharp 后，浏览器“袋里”调度插件都已卸载。
如果能再加个自动更新gfwlist功能，那真是太奢侈啦。感谢C大的分享与付出。。。

**Comment by dwbclz** [comment]
谢谢C大！
谢谢GangZhuo大~辛苦啦~
