### ISSUE TITLE
Why is this PAC doesn't look the same as the one exported from switchysharp?

### ISSUE THREAD

**Issue by nonozone** [shadowsocks/shadowsocks-csharp#116]
这个pac规则要怎么写啊？

**Comment by clowwindy** [comment]
谁有兴趣给楼主写个教程？

**Comment by nonozone** [comment]
额，我是看到里面有这样一句：
 if (hasOwnProperty.call(domains, host))
但是pac文件里貌似只有domains的内容，没有看到基于URL的过滤方式，我就是问问，类似switchysharp的URL过滤这一部分要怎么写，但又不是严格的正则。

**Comment by clowwindy** [comment]
如果是讨论和提问建议去论坛，这里没几个人会看，只处理 bug 反馈和功能建议。
