### ISSUE TITLE
作者可以在 github 放二进制包吗？

### ISSUE THREAD

**Issue by gonejack** [shadowsocks/shadowsocks-csharp#127]
作者更新得很勤快，在 https://github.com/shadowsocks/shadowsocks-csharp/releases 发布的话，大家可以看到release note，下载也容易，因为 sourceforce 老被墙。madeye 的 Shadowsocks Android Client 就是在 github 发布 APK 包的，感觉很方便。

**Comment by clowwindy** [comment]
https://github.com/shadowsocks/shadowsocks-csharp/issues/85
