### ISSUE TITLE
After the updates from GFWList your own rules are gone

### ISSUE THREAD

**Issue by ace7** [shadowsocks/shadowsocks-csharp#128]
希望改进这点，从GFWList更新PAC后保留自己添加的规则，谢谢！

**Comment by bombless** [comment]
你那是什么网站，可以参考项目所有者的建议把你的网站添加到 gfwlist 中。

**Comment by LazyZhu** [comment]
@clowwindy
貌似 @GangZhuo 写过 C# 版的 gfwlist2pac, 见此处:
https://github.com/shadowsocks/shadowsocks-csharp/commit/74c61ca76a3c032760c0b08190a6599b68ed4127
不过后来因为SS可以直接支持GFWList, 所以精简掉了
里面的代码可以实现user_rule.txt整合到pac.txt

另外我现在是用sed.exe添加到user_rule.txt到pac.txt, 虽然脚本非常慢, 但我不经常更新gfwlist :)
https://gnu-on-windows.googlecode.com/files/sed-4.2.2-bin.zip
https://gist.github.com/LazyZhu/8ca5eee44d6c9ccc9ac3

**Comment by ace7** [comment]
@bombless 有些网站可能并没有被墙，但是访问速度极慢，添加自定义规则后就能很流畅的访问。还有一些网站可能只是在某些地方才被墙。所以申请添加到 gfwlist 不一定成功而且麻烦，相反，自定义规则方便多了。

**Comment by GangZhuo** [comment]
当时还有一个办法是，读取pac.txt，并使用正则来替换掉var rules = []; 中的值。这样用户可以在var rules=[]; 外的任何地方写自定义规则。见 https://github.com/shadowsocks/shadowsocks-csharp/commit/075069ef167c3b4d9308d92ea47dc6543fabeec2

**Comment by clowwindy** [comment]
谁有更好的思路也可以提一下。

**Comment by ace7** [comment]
下面两个方法不知道可行不：
1. 添加 userDomains 变量，自定义规则写在里面；
2. 更新的时候只添加不删除

**Comment by lenovo-me** [comment]
config文件里加一个字段放自定义域名，更新的时候读取添加？

**Comment by hiddow** [comment]
也希望这方面能完善一下，现在都自定义不了规则了。本人小白

**Comment by everyx** [comment]
我也是由于这个问题退回到以前的版本，我支持 @ace7 的方法 1

**Comment by clowwindy** [comment]
谁有兴趣实现这个功能可以提个 pull request。

**Comment by clowwindy** [comment]
Fixed via #181

**Comment by clowwindy** [comment]
Released 2.3.1beta1
