### ISSUE TITLE
增加一个pac_user.txt吧，用户在这个文件里添加自定义网址，就不会更新pac.txt的时候覆盖曾自定义的网址了

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-csharp#129]
谢谢，希望大神有时间的时候可以考虑一下

**Comment by bombless** [comment]
其实我觉得可以设计一个精巧的结构把各个地区对不同网站的访问性记录下来，这样可以抓住相关的机房到底在什么位置。
当然也会导致SS被更迅速地封杀。相对坐以待毙我比较喜欢鱼死网破。
