### ISSUE TITLE
2.2版本，ipv6相关的bug

### ISSUE THREAD

**Issue by tontyoutoure** [shadowsocks/shadowsocks-csharp#131]
生成二维码功能不能很好的支持ipv6，会把地址的第一段当作是地址，第二段当作是端口，即使给地址加了方括号也是如此。如图所示。http://i.imgur.com/6VKfz72.png 第二行地址为生成二维码后扫描的结果。

**Comment by clowwindy** [comment]
谁有兴趣修这个 bug 可以发个 pull request。
