### ISSUE TITLE
本地端口一直都是8123

### ISSUE THREAD

**Issue by JamesMackerel** [shadowsocks/shadowsocks-csharp#133]
我还以为是1080呢，就在switchysharp里写了1080，**死活连不上**。后来选了全局模式看ie代理设置才知道所谓全局模式是改系统代理设置。然后回到pac模式，在switchysharp里用8123就能用了。
能不能让这个端口可选啊。

**Comment by Sharuru** [comment]
SwitchySharp的作者已推出了新版本插件：SwitchyOmega
我“情景模式”中，我进行了一下测试，能够使用设置的端口进行连接，以下是我的配置：
网址协议：“默认”（可能需要按实际情况更改）
代理协议：“SOCKS5”
代理服务器：“127.0.0.1”
代理端口：“1080”（即客户端“编辑服务器”功能中，“代理端口”所填的端口，可能需要按实际情况更改）
客户端设置：
开启“启用代理”
代理模式：“PAC模式”
未开启“在局域网共享”
请检查你的配置或者提供更多的消息。谢谢。

**Comment by bombless** [comment]
它的设计是这样的：8123是肯定占用的，用来获取 gfwlist 和版本更新信息，而且它是 HTTP 代理。

我不确定这里的问题是软件没有在监听 1080 呢，还是说没有按照 SOCKS5 来使用 1080。
参考 [README](https://github.com/shadowsocks/shadowsocks-csharp/blob/15f57a4d04f819944ae41eb94d6f2e1910926fd5/README.md)
```
4.Leave Enable menu unchecked, Shadowsocks will still provide an HTTP proxy at 127.0.0.1:8123
```
如果是在 Opera 下借助 Tampermonkey 上的 userscripts 装的 switchysharp，据我所知 Opera 的 Blink 版本是不支持 SOCKS 5 的。

总之我这里没能复现这个问题，看一下其他人有没有类似问题。
也可以看看服务器配置列表那里有没有打上勾，我不确定 GUI 方面会不会出现问题。

和 https://github.com/shadowsocks/shadowsocks-csharp/issues/102 重复

**Comment by john123951** [comment]
1080 使用Sock5协议，你再检查一下，不用管他8123端口的，走socket多快~

**Comment by clowwindy** [comment]
这么说起来，现在端口太多了。其实合并成一个就好了。

**Comment by clowwindy** [comment]
哈哈，有人想试试吗：
https://github.com/shadowsocks/shadowsocks-csharp/issues/136

**Comment by clowwindy** [comment]
Fixed in 18e6daf

**Comment by clowwindy** [comment]
2.3beta1 测试版：
http://sourceforge.net/projects/shadowsocksgui/files/dist/Shadowsocks-win-prerelease_2.3beta1.zip/download
