### ISSUE TITLE
可以考虑做成Windows服务吗？

### ISSUE THREAD

**Issue by zanpen2000** [shadowsocks/shadowsocks-csharp#134]
如题，做成Windows服务的话，局域网内就可以和同事们一起用了，而不用每次都登录进服务器才能运行软件了

**Comment by Sharuru** [comment]
局域网内共享可以使用客户端提供的“在局域网共享代理”功能，让你的同事将相关代理IP设置到你的机器所分配的IP就可以了。
比如PAC模式下，你本机的PAC地址是：http://127.0.0.1:8093/pac?t=一串数字，你被分配的内网地址是10.2.3.1的话，那么只要让你的同事将代理设置成http://10.2.3.1:8093/pac?t=一串数字即可使用你分享的代理了。
至于Windows服务以及”每次都登陆进服务器才能运行软件“我并没有看懂。如果是需要自启动客户端的话，程序本身就带有这个功能。

**Comment by clowwindy** [comment]
目前不考虑。可以自己找一找办法。
