### ISSUE TITLE
Why chrome says https connection is not secure

### ISSUE THREAD

**Issue by icase** [shadowsocks/shadowsocks-csharp#135]
IE下就是正常的，但是chrome下，选择pac模式，就提示不是安全链接。

**Comment by clowwindy** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/%E5%9B%9E%E5%A4%8D%E6%A8%A1%E7%89%88#%E6%97%A0%E6%B3%95%E9%87%8D%E7%8E%B0

**Comment by icase** [comment]
这个连接是啥意思，是无法重现？还是我的问题模板不对，求解惑。

**Comment by Septembers** [comment]
能截图吗
根据文字描述 我觉得可能是浏览器的DNS缓存导致的（Chrome内置异步DNS）

**Comment by icase** [comment]
![qq 20150118222530](https://cloud.githubusercontent.com/assets/5166123/5792700/0f20a148-9f61-11e4-8688-8fa8dc2d3fdb.jpg)

如图

**Comment by Septembers** [comment]
![](https://cloud.githubusercontent.com/assets/3842474/5792762/76a2e234-9f63-11e4-8596-cdc74638934d.png)

以下 **代理插件** 简称 **插件**

Chrome在**默认**未安装插件情况下**使用IE代理配置**
但是 **使用了插件** 插件会接管 **代理配置**
- 停用插件
- 设置插件的代理为"[系统代理]"

**Comment by icase** [comment]
OK了，解决了，但是为什么会出现这样的情况，我先前是选择了“直接连接”，这个难道不 等同于不经过任何代理直接访问么，还是客户端只能更改系统的(IE)的代理？
![qq 20150118225107](https://cloud.githubusercontent.com/assets/5166123/5792777/92ed9b68-9f64-11e4-9773-ebe825096d65.jpg)
