### ISSUE TITLE
After update PAC from GFWList, IE11 unable to visit www.google.com

### ISSUE THREAD

**Issue by huawuxin** [shadowsocks/shadowsocks-csharp#137]
此问题 https://www.v2ex.com/t/162251 的147楼有人提过，似乎没引起注意。

我来补充下我了解的情况：

1、这个问题其实是PAC模式对（IE9、IE10、）IE11的问题，跟Windows 8无关。Windows 7下把自带的IE8升级成IE11，也会遇到这个问题。

2、出问题时“代理模式”选的是“PAC模式”，“启用代理”已打勾。此时Chrome 39.0.x和IE8都是可以正常出墙的，但是IE11就是不行。

3、目前直到2.2.1版本的exe，想要IE11能出墙，“代理模式”必须选“全局模式”才行。

**Comment by huawuxin** [comment]
出问题时代理设置是正确（符合预期）的，如下图所示。同样的设置IE8时正常。

![lan settings](https://cloud.githubusercontent.com/assets/2068446/5791115/b9ff6d8a-9ef6-11e4-8809-ac47e94258e2.jpg)

**Comment by bombless** [comment]
我可以确定不是所有的 IE11 都不行……我切换全局代理或者用 PAC 模式都没问题
我是 8.1 64位
不过我试的是上一个版本，这个版本没事过
看 [修改历史](https://github.com/shadowsocks/shadowsocks-csharp/commits/40aded9571ff5e78c89aa6b554f4ee15ab76c065/shadowsocks-csharp/Controller/SystemProxy.cs)  好像没看到最近改过这个方面

**Comment by clowwindy** [comment]
147 楼说的是是否PAC，都无法连接代理服务器。而你的情况是 PAC 不行，全局可以。我猜是你的 PAC 语法有问题或者被改坏了。

每一条回复我都看了，但是在每天收到十几条的情况下，没力气会回复这些没有具体操作步骤的。你要花好大力气去教他怎么写一个步骤出来。有时我这么去问的时候，被问的人又懒了，说可能是小问题吧，然后又算了。

**Comment by huawuxin** [comment]
感谢作者的回复。根据回复的提示我做了试验，“PAC 语法有问题或者被改坏了”这个猜测是对的：“从GFWList更新PAC”功能生成的PAC文件，不适用于IE11。

实验步骤：

1、退出exe，删掉exe所在文件夹里的pac.txt。再重新运行exe，“代理模式”选“PAC模式”，勾选“启用代理”。此时IE11可以出墙。

2、点击从“从GFWList更新PAC”菜单，等待提示更新成功。此时IE11不能出墙了。

100%重现。

**Comment by clowwindy** [comment]
具体是什么网站不行

**Comment by huawuxin** [comment]
www.google.com

**Comment by huawuxin** [comment]
根据回复给我的提示，我做了更多的试验。现在发现我这问题报告真的是少了很多关键信息，真是抱歉。

从“从GFWList更新PAC”后，http://www.google.com/、https://www.google.com/ 和 https://www.google.com/?gws_rd=ssl （这个是未自动更新PAC前访问google会自动跳转到的URL）都打不开；但 https://www.facebook.com/ 和 https://twitter.com/ 可以正常打开。

为了避免又漏掉关键信息，我啰嗦下：我的电脑主DNS服务器是192.168.1.1（路由器），备用DNS服务器空着；路由器的DNS是8.8.4.4和223.6.6.6。

**Comment by Septembers** [comment]
可能是Winsock的问题
可以尝试用[Complete Internet Repair](http://www.rizonesoft.com/software/complete-internet-repair/)工具修复一下

**Comment by huawuxin** [comment]
@Septembers 已试，问题照旧。

                                            ./
                                          (o o)
--------------------------------------oOOo-(_)-oOOo--------------------------------------
[18/01/2015 23:07:02] Attempting to reset Winsock catalog, Please wait.....
-----------------------------------------------------------------------------------------
[18/01/2015 23:07:02] Successfully reset the Winsock Catalog.
[18/01/2015 23:07:02] Finished repairing Winsock

-----------------------------------------------------------------------------------------
[18/01/2015 23:07:02] You will need to reboot your computer before the settings will take effect.
-----------------------------------------------------------------------------------------
[18/01/2015 23:07:16] Your computer is restarting now.....

-----------------------------------------------------------------------------------------

**Comment by lenovo-me** [comment]
1、命令行运行nslookup www.google.com，贴下结果
2、把pac传上来看看

**Comment by GangZhuo** [comment]
测试了下应该是 PAC 文件有问题。 IE11很奇怪，新建一个test.htm，引用pac文件，然后在控制台中直接执行他的FindProxyForURL('http://www.google.com/', 'www.google.com')方法，能够正确返回 'PROXY 127.0.0.1:1080;'，但是在pac.txt的FindProxyForURL函数中加一行 alert(defaultMatcher.matchesAny('http://www.google.com/', 'www.google.com'));然后在IE中访问http://www.google.com时，却弹出'null'。

**Comment by huawuxin** [comment]
@lenovo-me 

【全局模式时，已先用IE11访问www.google.com，可打开】
C:\Windows\system32>nslookup www.google.com
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    www.google.com
Addresses:  2404:6800:4005:804::1014
          64.233.187.104
          64.233.187.106
          64.233.187.105
          64.233.187.147
          64.233.187.99
          64.233.187.103

【PAC模式时，已先用IE11访问www.google.com，打不开】
C:\Windows\system32>nslookup www.google.com
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    www.google.com
Addresses:  2404:6800:4005:804::1014
          64.233.187.104
          64.233.187.106
          64.233.187.105
          64.233.187.147
          64.233.187.99
          64.233.187.103

PAC文件因为这里只给传图片，我就不上传了。反正就是exe的“从GFWList更新PAC”功能自动下到的版本，随便时候下到的都可以。

**Comment by huawuxin** [comment]
@GangZhuo 我这个外行也觉得PAC文件嫌疑很大，毕竟同等条件下exe自带的PAC就正常。

**Comment by GangZhuo** [comment]
应该是 IE 11 的BUG。 见下图。在判断是否是正则时，出错。代码如下：
if (regexpSource.length >= 2 && regexpSource[0] == "/" && regexpSource[regexpSource.length - 1] == "/")
    {
        var regexp = new RegExp(regexpSource.substr(1, regexpSource.length - 2), this.matchCase ? "" : "i");
        this.regexp = regexp;
		alert('this.regexp: ' + this.regexp);
    }
    else
    {
        this.regexpSource = regexpSource;
    }

![capture](https://cloud.githubusercontent.com/assets/1397462/5798791/2516119e-9f99-11e4-8815-7ea74db0da79.PNG)

**Comment by clowwindy** [comment]
2.3beta2:
https://sourceforge.net/projects/shadowsocksgui/files/dist/

**Comment by huawuxin** [comment]
已试2.3，从GFWList更新PAC后，PAC模式时还是打不开www.google.com。
已试多遍，每次都不行。也确定是用的新（2.3）版。

**Comment by GangZhuo** [comment]
需要使用Shadowsocks-win-prerelease_2.3beta**2**.zip，我在家里windows 8.1 ie11也测试了，可以的。

**Comment by huawuxin** [comment]
囧，我真是下错文件了。

**Comment by GangZhuo** [comment]
不知道ie的bug应该在哪里提交，谁知道的去提交下吧

**Comment by JerryJhou** [comment]
https://connect.microsoft.com/ie/
IE 的 Feedback页面
我这个外行不太懂，懂的人提交一下吧
