### ISSUE TITLE
更新微软.Net Framework补丁(KB2901983)后运行SS出错

### ISSUE THREAD

**Issue by thelastfantasy** [shadowsocks/shadowsocks-csharp#138]
系统WIN7 64位
SS用的是Shadowsocks-win-2.2.1.zip
http://i.imgur.com/KNH9CJn.png
控制面板看了下好像该补丁不提供卸载

**Comment by huawuxin** [comment]
这错误今天我也见过，重启系统后好了。

**Comment by clowwindy** [comment]
换个端口。
