### ISSUE TITLE
如何在windows中做ARP欺骗，分享给局域网中其他电脑使用

### ISSUE THREAD

**Issue by icase** [shadowsocks/shadowsocks-csharp#142]
这个有办法做到么，类似fqrouter的pick的功能。

**Comment by lenovo-me** [comment]
不是有share over lan么

**Comment by icase** [comment]
share over lan选上了，所有的局域网内设备都会自动代理？

**Comment by GangZhuo** [comment]
https://www.google.com.hk/search?q=WPAD

**Comment by Sharuru** [comment]
建议在发布新 issue 前妥善使用搜索功能。
issue #73 应该可以解答你有关PC共享的疑问，
同时 issue #83 应该可以解答你有关移动设备共享的疑问。
请注意，由于版本的更新，issue #73 中所提到的 PAC 端口 8090 已经更改至 8093

**Comment by crazygo** [comment]
@GangZhuo 这个是需要在dns服务器上的配置吧，自己的电脑怎么设置成dns服务器呢？

**Comment by icase** [comment]
@Sharuru 这两个问题跟我提出的问题并不一样，我看了一下，这还是基于要在所使用的设备上填写PAC地址或者是share ss的设备上的地址，而我是想了解一下，能否如fqrouter之前的效果一样，我可以在被分享的设备上不做任何设置，即可使用主机的ss服务。或者说，sharuru你有计划开发么？

**Comment by sd362318** [comment]
share over lan后还得再其他设备上设置代理？

**Comment by myliyifei** [comment]
对的  相当于提供一个公共代理服务器。
2015年1月27日 上午9:43于 "sd362318" <notifications@github.com>写道：

**Comment by clowwindy** [comment]
Fixed in f4007b685b7067fbfc85cb662c72beaac134bb58
