### ISSUE TITLE
从gfwlist更新的pac名单里竟然没有google.com

### ISSUE THREAD

**Issue by thundercn** [shadowsocks/shadowsocks-csharp#144]
如题，更新pac后在pac模式下无法打开google.com，但是youtube可以，查来查去发现原来pac文件里竟然没有google.com。手动添加之后就可以访问google了。不知这个问题出现在哪里，期待解决。

**Comment by Sharuru** [comment]
经测试，在当前版本 2.2 中，使用“从 GFWList 更新 PAC”可以更新 PAC 文件。更新的 PAC 文件在 1076 行附近开始有关于 Google 以及相关服务的相关规则，请确认。
同时也请确认 Shadowsocks 客户端所在目录可写。
在更新 PAC 文件后你可能需要手动启用、停用代理一次以让新的 PAC 文件生效。

有关 GFWList 规则问题请提交至对应 REPO。

**Comment by thundercn** [comment]
谢谢，最新下载的beta版已经没有问题。
