### ISSUE TITLE
为什么ss手机客户端的速度比电脑客户端快呢？

### ISSUE THREAD

**Issue by snoa1** [shadowsocks/shadowsocks-csharp#145]
ss手机端的速度比电脑端快，同一个服务器同一个youtube视频，手机端看1080p都不卡，电脑端720p都卡，这是为什么呢?

**Comment by snoa1** [comment]
问反了，应该是为什么电脑端比手机端慢- -

**Comment by clowwindy** [comment]
https://www.v2ex.com/t/164507#reply7
