### ISSUE TITLE
感觉有时候代理的效率不够高

### ISSUE THREAD

**Issue by nonozone** [shadowsocks/shadowsocks-csharp#148]
有时候会出现这种情况，比如某条网址已经在规则里面了。访问网站的时候，会发现某些图片无法显示，比如一个图片列表，有一部分图片不显示，等好几秒钟都是，图片的地址肯定是在规则里的。这个时候F12打开调试模式，这些图片貌似一下子就显示出来。

**Comment by Sharuru** [comment]
https://www.v2ex.com/t/164507#reply7

**Comment by clowwindy** [comment]
http://nwmon.tifan.net/kddi/index-24h.html
