### ISSUE TITLE
IE 不走 Shadowsock for Windows PAC

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-csharp#150]
不知道什么原因。。

**Comment by Sharuru** [comment]
请确认：
1. 使用的是最新版本的 Shadowsocks 客户端。
2. 右键单击打开 Shadowsocks 客户端托盘菜单，“启用代理”是被勾选的，同时“代理模式”下“PAC 模式”是被启用的。
3. PAC 文件内容不为空。
4. 在 IE 中，通过“Internet 选项”——“连接”选项卡——“局域网设置”按钮打开“局域网(LAN)设置”对话框，“自动配置”组下“使用自动配置脚本”被勾选，“地址”文本框内容类似：”http://127.0.0.1:8093/pac?t=201501231332144165“。
5. Shadowsocks 所在文件夹可读可写。

注意：如果你手动修改了 PAC 文件，你可能需要重新启用一次代理功能来让新的配置文件生效。

在确认以上五项设置均无问题后，如果依然无法应用 PAC 配置，请提供更多的信息。

**Comment by LisonFan** [comment]
1、使用的是2.3 beta 2的Shadowsocks
2、启用代理是勾选的，代理模式下是PAC模式
3、使用了Shadowsocks的自动更新gfwlist，不为空。
4、http://127.0.0.1:1080/pac?t=201501232240563751 Shadowsocks自动生成的地址。
5、可读写。

Chrome用PAC都正常，然后Shadowsocks用全局模式 IE 走Shadowsocks。
刚刚发现 IE 也走 PAC ，是PAC的文件没有把Google相关链接写进去....

**Comment by LisonFan** [comment]
初步怀疑 IE 不支持 “ "/^https?:\\/\\/[^\\/]+google\\.(.*)/", ” 这句语法？

**Comment by GangZhuo** [comment]
2.3beta2下重新更新下pac，这个正则不匹配http(s)://google.com，匹配http(s)://www.google.com

**Comment by LisonFan** [comment]
@GangZhuo http(s)://www.google.com 也不匹配

**Comment by LisonFan** [comment]
@GangZhuo *.*google*.* 都无法访问

**Comment by GangZhuo** [comment]
看 https://github.com/shadowsocks/shadowsocks-csharp/issues/137，不知道是否是同一问题

**Comment by LisonFan** [comment]
@GangZhuo 应该是同一个问题

**Comment by LisonFan** [comment]
@GangZhuo 删了从gfwlist更新生成的PAC.txt文件 IE就能访问Google

**Comment by GangZhuo** [comment]
那个问题在 2.3beta2中已经解决了，你可以试看看

**Comment by LisonFan** [comment]
@GangZhuo 在2.3beta2中并没有解决，我现在就是用的beta2，PAC模式 IE 无法访问Google。Chrome无法检测更新，Chrome检测更新必须全局

**Comment by LisonFan** [comment]
@GangZhuo 额..莫名其妙的现在用2.3beta2 从GFWlist更新PAC 之后 IE 能访问Google了...
但是 PAC模式下 Chrome无法检测更新还没解决

**Comment by Sharuru** [comment]
Windows 下的 Chrome 使用 IE 的代理设置，所以需要设置全局模式或者合理的 PAC 文件。
也许是你的 PAC 文件不包含 Chrome 更新所需要的域名。

**Comment by LisonFan** [comment]
@Sharuru 我的PAC文件是通过GFWlist获取的

**Comment by Sharuru** [comment]
通过 GFWList 获取并不代表 PAC 文件内含有 Chrome 更新所需要的域名。

**Comment by LisonFan** [comment]
@Sharuru @clowwindy 希望大神们有空的时候能在PAC里加上Chrome更新所需要的相关域名，有劳了。

**Comment by lenovo-me** [comment]
@LisonFan https://www.v2ex.com/t/162251 看附言:)
