### ISSUE TITLE
我觉得PAC模式下chrome检测更新不走Shadowsocks不是gfwlist的问题

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-csharp#154]
同样的PAC文件在Mac上PAC模式下chrome检测更新正常

**Comment by LazyZhu** [comment]
@clowwindy
这个可能是PAC的http服务的问题, 客户端有时候会无法获取pac内容, 如图:
![2015-01-27_015256](https://cloud.githubusercontent.com/assets/2244967/5905055/28a5cdd8-a5c8-11e4-9db3-fb2c55c26256.png)
这个问题也会出现在Firefox上. 但是只要客户端有pac内容的缓存就ok

**Comment by clowwindy** [comment]
PAC 端口是 1080

**Comment by LazyZhu** [comment]
我设置的8080

**Comment by clowwindy** [comment]
不知道你这个是什么软件，如果中间环节太多就无法排错，建议把系统代理关掉，然后直接用浏览器打开这个 URL 看看具体是什么问题，404 还是什么

**Comment by LazyZhu** [comment]
没开系统代理，就是把设置了chrome的扩展的PAC代理，浏览器打开的话显示下载，而不是内容，header参数问题？

**Comment by clowwindy** [comment]
显示下载是对的。浏览器能下载，并且下载内容没有问题的话，说明 PAC 没有问题。

**Comment by LazyZhu** [comment]
但是Chrome/Firefox更新pac都会卡顿/无响应
![2015-01-27_163858](https://cloud.githubusercontent.com/assets/2244967/5915633/0b75f5c8-a643-11e4-828f-10e7e18654bc.png)

**Comment by clowwindy** [comment]
如果文件能正常下载，内容也是对的，那服务器这边没有什么能做的了，建议向 SwitchyOmega 提交 issue。

**Comment by GangZhuo** [comment]
测试了下，SwitchyOmega 中点击 Download Profile Now 按钮后，速度很快....
