### ISSUE TITLE
password in gui-config.json should be encryption

### ISSUE THREAD

**Issue by maxsky** [shadowsocks/shadowsocks-csharp#155]
use any text editor open gui-config.json file will see text password....so i think "password" : should be encryption, its safer

**Comment by myliyifei** [comment]
我也建议做一个简单的加密就好了。

**Comment by clowwindy** [comment]
Safer for what? If you give other people access to your PC, they can just copy your configuration file to their PC. If you don't, why do you need to encrypt a file that only you have access to?
