### ISSUE TITLE
Feature request: UI to configure polipo

### ISSUE THREAD

**Issue by FrankHB** [shadowsocks/shadowsocks-csharp#156]
I found ss_polipo.exe establishing connections on port 8123. This has caused me being banned by freenode.net when I [used an IRC client on the same host](https://freenode.net/policy.shtml#proxies),

```
You are banned from this server- Your host is an open proxy (HTTP POST (8123)).  Email proxyscan@freenode.net when corrected.
```

I found `polipo.conf` is in my `%TMEP%` directory. The default behavior is not convenient to change. A GUI to configure may help.

**Comment by clowwindy** [comment]
This seems to be a rare case. You might want to compile a special version for you.
