### ISSUE TITLE
建议 ss 的 win 客户端加入 socks协议的 用户验证功能

### ISSUE THREAD

**Issue by xenocide** [shadowsocks/shadowsocks-csharp#157]
建议 ss 的 win 客户端加入的 1080 的 socks 用户验证功能，否则在开启 lan 代理共享的条件下， 1080 端口很容易被扫描，然后 ss 被利用发垃圾邮件。这直接导致了我的搬瓦工 vps 被封了。

开始一直没发现原因，以为是vps上的问题，最近才发现原因所在。希望@clowwindy 能加入这种功能，不然对于需要开启LAN共享，又处在不安全的局域网环境（我是校园局域网），ss客户端很容易成为被攻击利用的漏洞。

**Comment by myliyifei** [comment]
可以用防火墙封锁一部分，然后VPS上封锁25端口。当然能加入share over lan 的身份验证是更好了。

在 2015年1月29日 下午3:54，xenocide <notifications@github.com>写道：

**Comment by josephzjw** [comment]
+1我也碰到这个问题了。。。结果关了就好了。。。想不到校园网也有hacker。。。
