### ISSUE TITLE
windows 8.1 不可用

### ISSUE THREAD

**Issue by zhuer0632** [shadowsocks/shadowsocks-csharp#164]
windows 8.1 不可用

[2015-02-01 20:52:14] System.InvalidOperationException: 没有与此对象关联的进程。
在 System.Diagnostics.Process.EnsureState(State state)
在 System.Diagnostics.Process.EnsureState(State state)
在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
在 System.Diagnostics.Process.Kill()
在 Shadowsocks.Controller.PolipoRunner.Stop()
[2015-02-01 20:52:15] System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
在 System.Diagnostics.Process.Start()
在 Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
在 Shadowsocks.Controller.ShadowsocksController.Reload()

**Comment by clowwindy** [comment]
8.1 测试可用。

**Comment by cielpy** [comment]
Win10报了这个错。
