### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by frankdai** [shadowsocks/shadowsocks-csharp#165]
Windows XP SP3
应用程序正常初始化(0xc0000135)失败。请单击确定，终止应用程序。

**Comment by clowwindy** [comment]
https://www.google.com/search?q=%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E6%AD%A3%E5%B8%B8%E5%88%9D%E5%A7%8B%E5%8C%96(0xc0000135)%E5%A4%B1%E8%B4%A5&ie=utf-8&oe=utf-8&aq=t&gws_rd=ssl
