### ISSUE TITLE
Unable to handle openvpn udp requests

### ISSUE THREAD

**Issue by i8s301a** [shadowsocks/shadowsocks-csharp#166]
Dear developers,

I am tunneling openvpn udp packets over shadowsocks with the directive from this page https://github.com/shadowsocks/shadowsocks/wiki/Connect-to-OpenVPN-over-Shadowsocks.

Everything works fine with shadowsocks python client (sslocal) on Windows with either shadowsocks python server or libev server on Linux, which both support UDP relay functionality. The openvpn server and shadowsocks server are running on the same Linux box.

However, after switching to shadowsocks-csharp client (version 2.0.11 to latest 2.3), it seems openvpn client is no longer able to connect the server over shadowsocks. There is no error or any other output in shadowsocks' log while the openvpn log reads as follows:

> ...
> Tue Feb 03 01:37:46 2015 Attempting to establish TCP connection with [AF_INET]127.0.0.1:1080 [nonblock]
> Tue Feb 03 01:37:46 2015 MANAGEMENT: >STATE:1422898666,TCP_CONNECT,,,
> Tue Feb 03 01:37:46 2015 TCP connection established with [AF_INET]127.0.0.1:1080
> Tue Feb 03 01:37:46 2015 UDPv4 link local: [undef]
> Tue Feb 03 01:37:46 2015 UDPv4 link remote: [AF_INET]172.16.55.55:xxxxx {P.S.: 172.16.55.55 is the private IP address of the openvpn/shadowsocks server which is accessible from shadowsocks; I had also attempted to change the target IP address to 127.0.0.1 or server's public IP in openvpn config but also no avail.}
> Tue Feb 03 01:37:56 2015 write UDPv4: The requested address is not valid in its context. (code=10049) {P.S.: The error message turns to "us=791941 UDPv4 READ [0] from [undef]: DATA UNDEF len=0" if output level of openvpn client is raised from 3 to 6.}
> ...

For reference, openvpn client output shall read as follows if packets are successfully relayed over shadowsocks:

> ..
> Tue Feb 03 01:50:04 2015 Attempting to establish TCP connection with [AF_INET]127.0.0.1:1080 [nonblock]
> Tue Feb 03 01:50:04 2015 MANAGEMENT: >STATE:1422899404,TCP_CONNECT,,,
> Tue Feb 03 01:50:04 2015 TCP connection established with [AF_INET]127.0.0.1:1080
> Tue Feb 03 01:50:04 2015 UDPv4 link local: [undef]
> Tue Feb 03 01:50:04 2015 UDPv4 link remote: [AF_INET]172.16.55.55:xxxxx
> Tue Feb 03 01:50:14 2015 Peer Connection Initiated with [AF_INET]172.16.55.55:xxxxx
> ...

Please let me know if further infromation is required so that the issue could be tracked and solved in future releases.

**Comment by clowwindy** [comment]
As stated in the wiki, you can only tunnel OpenVPN over Python / node.js server and client.
