### ISSUE TITLE
建议取消自动更改ie浏览器代理设置

### ISSUE THREAD

**Issue by hetykai** [shadowsocks/shadowsocks-csharp#167]
感觉这样反而麻烦了，每次打开就得重新把ie代理设置关闭掉。我一般都是用chrome+proxyswichy，很少用ie浏览器，但是如果更改ie浏览器的代理设置就会影响到很多软件的正常运行，比如一些用系统代理设置的软件，比如有道词典、sublime等等很多常用的软件。
所以强烈建议把自动更改ie代理设置的功能取消掉，或者弄一个开关。

**Comment by clowwindy** [comment]
不选“启用系统代理”这个选项就行了，这个选项默认就是关的。

**Comment by hetykai** [comment]
My shadowsocks`language is chinese, and i can`t find the "Enable System Agent" option, where is the option? Or how i can chang the software`s language?

**Comment by CNMan** [comment]
https://github.com/shadowsocks/shadowsocks-csharp/blob/master/shadowsocks-csharp/Data/cn.txt

**Comment by clowwindy** [comment]
The FIRST option in the menu.

**Comment by hetykai** [comment]
Tks, i find it and handle it.
