### ISSUE TITLE
a test button for connectivity

### ISSUE THREAD

**Issue by yfdyh000** [shadowsocks/shadowsocks-csharp#170]
For example, shows connectivity to google.com by specific server, for faster troubleshooting.

ideas:
Placed in the edit server window, the button on the left side of the proxy port box, the result text on the lower left corner of window, or a icon on server frame.
and if have show a delay ms here, may be better.

**Comment by Sharuru** [comment]
Due to issue #98 and #100, author may not realizing this feature, you can try it by yourself. :smile:

**Comment by yfdyh000** [comment]
Thanks.
