### ISSUE TITLE
shadowsocks支持转发UDP吗？

### ISSUE THREAD

**Issue by nsznsznsz** [shadowsocks/shadowsocks-csharp#171]
给酷狗设置SOCK5代理时无法连接 给QQ设置时可以
不过我用浏览器连sock5是可以连上的
但酷狗必须设为HTTP代理才能连上 

而我用CCProxy的sock5时 酷狗是可以连上的 
是不是udp转发的部分有问题？
![zz](https://cloud.githubusercontent.com/assets/10374085/6098612/b67c1caa-b01f-11e4-9ffe-7882d9239007.jpg)

**Comment by clowwindy** [comment]
不支持。
