### ISSUE TITLE
ss_polipo.exe 已停止工作

### ISSUE THREAD

**Issue by justrover** [shadowsocks/shadowsocks-csharp#175]
![3277491387 chatroom_1424018964847_188](https://cloud.githubusercontent.com/assets/11018462/6204068/cb20b866-b577-11e4-8b70-f0e8b25a5829.jpg)

Shadowsocks-win-2.3
版本是2.3.0.0，系统win7 64位，
情况发生在：

使用QQ浏览器8.0.2的微信发送QQ截图时会立即弹出此提示。
我只用原版Google Chrome浏览器来使用Shadowsocks，可是桌面版微信的话用QQ浏览器内置的微信才好，可是QQ浏览器也是Chrome内核，我并没想让QQ浏览器接代理，但不知道如何设置。

**Comment by justrover** [comment]
[2015-02-16 01:17:15] Shadowsocks started
[2015-02-16 01:17:53] System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)


以上是出错时的日志记录。使用PAC模式也一样。

**Comment by FuckTheGFW** [comment]
请到 计算机管理>事件查看器>Windows日志>应用程序 寻找相关的错误记录

**Comment by Provissy** [comment]
让浏览器走Socks
