### ISSUE TITLE
ss_polipo.exe已停止工作

### ISSUE THREAD

**Issue by kj54321** [shadowsocks/shadowsocks-csharp#176]
![qq 20150216215052](https://cloud.githubusercontent.com/assets/10719141/6212946/88fbb324-b625-11e4-8797-ca8748256585.png)

错误日志：
[2015-02-16 21:51:03] System.InvalidOperationException: 进程已退出，因此无法处理请求。
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.PolipoRunner.Stop()

使用情况描述：
WIN7 64位 电脑开SS2.3（没有进程/游览器使用），PS4设置好后连接仅几秒钟即报错。
望大师排查原因，谢谢了

**Comment by kj54321** [comment]
日志名称:          Application
来源:            Application Error
日期:            2015/2/16 21:50:09
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           FPE1HCWMNO0BON1
描述:
错误应用程序名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
错误模块名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
异常代码: 0x40000015
错误偏移量: 0x00002d9a
错误进程 ID: 0x14c0
错误应用程序启动时间: 0x01d049ef74e7b335
错误应用程序路径: C:\Users\Administrator\AppData\Local\Temp\ss_polipo.exe
错误模块路径: C:\Users\Administrator\AppData\Local\Temp\ss_polipo.exe
报告 ID: b7e5e0db-b5e2-11e4-b542-300ed5ba688a
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-02-16T13:50:09.000000000Z" />
    <EventRecordID>82791</EventRecordID>
    <Channel>Application</Channel>
    <Computer>FPE1HCWMNO0BON1</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ss_polipo.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>548d68ee</Data>
    <Data>ss_polipo.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>548d68ee</Data>
    <Data>40000015</Data>
    <Data>00002d9a</Data>
    <Data>14c0</Data>
    <Data>01d049ef74e7b335</Data>
    <Data>C:\Users\Administrator\AppData\Local\Temp\ss_polipo.exe</Data>
    <Data>C:\Users\Administrator\AppData\Local\Temp\ss_polipo.exe</Data>
    <Data>b7e5e0db-b5e2-11e4-b542-300ed5ba688a</Data>
  </EventData>
</Event>

**Comment by dawnchen** [comment]
又遇到此错误，windows 8.1， shadowsocks 2.5.1，启用系统代理，全局模式，用IE从MSDN直接下载VS2015 ISO，貌似两次都是接近2GB的时候就报此错误，下载中断。

日志名称:          Application
来源:            Application Error
日期:            2015/8/3 15:11:37
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           dawn-thinkpad
描述:
错误应用程序名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
错误模块名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
异常代码: 0x40000015
错误偏移量: 0x00002d9a
错误进程 ID: 0x31dc
错误应用程序启动时间: 0x01d0cdb16e896b9d
错误应用程序路径: C:\Users\Dawn\AppData\Local\Temp\ss_polipo.exe
错误模块路径: C:\Users\Dawn\AppData\Local\Temp\ss_polipo.exe
报告 ID: e09bb47d-39ae-11e5-82db-28d244f2cf27

**Comment by simbatony** [comment]
我也遇到这个问题了

**Comment by dawnchen** [comment]
请下载最新版的SS.

**Comment by simbatony** [comment]
谢谢你，问题解决了
