### ISSUE TITLE
无法支持超过256字节以上的密钥

### ISSUE THREAD

**Issue by cyyself** [shadowsocks/shadowsocks-csharp#177]
我自己搭建的SS密钥是随机生成的，接近500字节，这个版本的SS的ConfigForm.cs中，PasswordTextBox的MaxLength值为256，无法装下我的全部密码，只好到config.json中自己改，对一些用户体验影响甚大，建议修改。

**Comment by cyyself** [comment]
C#中TextBox的MaxLength为32767

**Comment by clowwindy** [comment]
没意义，熵的池子就 32 字节。
