### ISSUE TITLE
弱弱地冒一句中文，怎么push pac列表？

### ISSUE THREAD

**Issue by micln** [shadowsocks/shadowsocks-csharp#180]
我遇到一些网站需要出去，自己改了换个地方又得改。

估计其他人也遇到类似问题。

所以请问，上哪里找ss的这份列表。。。

**Comment by Sharuru** [comment]
"换了地方"是指什么呢？

要在多台电脑配置 pac 的话，复制 `pac.txt` 进行替换即可。

Shadowsocks-csharp 默认使用的 pac 文件位于程序的根目录下。
你可以右击托盘图标，选择“编辑 PAC 文件…”功能直接打开程序根目录，`pac.txt` 即为使用到的 pac 文件。

如果你使用的是 GFWList 提供的 pac，请至对应 Repo 进行反应。
