### ISSUE TITLE
请让来自局域网的连接也支持PAC

### ISSUE THREAD

**Issue by li3shiyi** [shadowsocks/shadowsocks-csharp#182]
现在的版本即使勾选了允许来自局域网的连接，pac文件里的代理用的还是 127.0.0.1:1080。请改成本机局域网IP。

**Comment by myliyifei** [comment]
我估计解决方案，IE浏览器里面应该可以指向 SS 服务器的那个PAC把，但是要换全部的IP？

在 2015年3月6日 下午3:24，li3shiyi <notifications@github.com>写道：

**Comment by clowwindy** [comment]
这个功能是有的，在我这里也是好的。如果你觉得发现了一个 bug，请详细描述每一步让其他人可以重现这个 bug。如果你无法让别人重现，尝试自己解决。
https://github.com/shadowsocks/shadowsocks-csharp/blob/master/shadowsocks-csharp/Controller/PACServer.cs#L117-L121

**Comment by Sharuru** [comment]
本机显示的永远是 127.0.0.1
不仅仅是代码量也是基于效率考虑。
如果要在其他机器使用请替换成“服务端”的局域网 IP 才行。

请善用搜索功能。
你的问题可能和这个 issue 有关 #73
