### ISSUE TITLE
IE proxy settings can only be modified once during a instance's life

### ISSUE THREAD

**Issue by krrr** [shadowsocks/shadowsocks-csharp#184]
The method used here is very popular (no one even changed variable names of last two return values), but it has the problem as described above. Maybe my case is rare? (If not, why nobody report this...)
Here is a [example](http://stackoverflow.com/questions/2059285/why-can-i-change-the-registry-only-the-first-time)
(my windows is 7 home basic, with sp1)

**Comment by clowwindy** [comment]
Find a solution and send a pull request.
