### ISSUE TITLE
Please support accessing via domain like www.example.com

### ISSUE THREAD

**Issue by zhaowy64** [shadowsocks/shadowsocks-csharp#189]
RT, because of someting in pilpo misconfigured (virtual hosting, i think.), when accessing my pac file via http://www.example.com:1080/pac pilpo will return a 404 code. But accessing via IP:1080/pac works fine.

还是说中文吧（英文太烂请见谅）：
我想用类似 http://subdomain.example.com:1080/pac 直接访问 ss 的 pac 文件，而不是用 IP地址，因为我得到的 IP地址是动态的，不方便每次开机都手动输入。
笔记本和 iPad 在同一个子网里，不存在相互之间的链接问题（实际上是在同一个交换机下）。

重现步骤：
1. A电脑安装最新客户端并且接受来自局域网的连接；
2. B电脑设置 hosts 文件 使任意域名（非A电脑加本地dns后缀）指向A电脑 IP地址
3. B电脑访问 http://域名:1080/pac

现象：
![image](https://cloud.githubusercontent.com/assets/6920098/6574175/19b2e5a2-c75d-11e4-9d33-bf4e77e073d2.png)

**Comment by clowwindy** [comment]
No plan for this. You can modify the code yourself or ask a friend to do so.

**Comment by ssc19940105** [comment]
IPV4下127.0.0.1就直接代表本机

**Comment by Septembers** [comment]
在Windows环境下可用 **机器名** 代替 **IP**

**Comment by zhaowy64** [comment]
不幸的是我使用的既不是本地IP，也不是Windows环境。。。
换句话说显然在 Request Header 里会有 hostname ，几乎是不可能直接用IP地址或者localhost来访问的

现在有点思路是修改polipo的配置，让所有指向本机的地址都redirect 到IP地址加端口，或者shadowsocks支持虚拟主机

**Comment by dangyuluo** [comment]
有想法了么？我正在调试，但是发现使用域名访问的话，都不能进入 PACServer这块
