### ISSUE TITLE
一个建议：能否加入SS节点连通性检测

### ISSUE THREAD

**Issue by qq50666** [shadowsocks/shadowsocks-csharp#192]
好多人用的免费的SS代理，用的人一多连通性就是个问题!
今天在一个Q群看到有人在一个一个ping，突然想到，有没有可能把该功能集成到shadowsocks-gui中，测试的速度显示到右键菜单中的节点后边可以用分隔符；如果可以实现或许再加个“是否自动检测“的开关更好，用户可以自行选择！

**Comment by chenping2015** [comment]
行啊！方便大家都能用。

- 发送自我的Sony Xperia™智能手机

---- 石头 编写 ----

**Comment by Sharuru** [comment]
See issue #170

**Comment by chenping2015** [comment]
需要具备哪些条件呢？实话，我这方面是个菜鸟！
2015年3月13日 下午10:35于 "Sharuru" <notifications@github.com>写道：

**Comment by Sharuru** [comment]
请问你阅读了引用 issue 中的文字了么？
> 影响使用感受的因素太多，ping 值低不代表速度就快，刷网页快的不一定看视频就快，而且网络本身就是不稳定的，前几分钟快的可能下几分钟就慢了，除了真的使用一会儿之外并没有太好的比较服务器速度的办法。

简单来说，一个服务器的速度快慢与否，并不能简单地依靠 ping 值来进行判断。故添加这个功能的实际意义并不大，但如果想要实现这个功能，欢迎你贡献代码。 :smile:

**Comment by chenping2015** [comment]
代码 就是Mac?
2015年3月13日 下午10:47于 "Sharuru" <notifications@github.com>写道：

**Comment by chenping2015** [comment]
我需要具备啥条件啊？且，我已经用上SS了。

- 发送自我的Sony Xperia™智能手机

---- clowwindy 编写 ----

**Comment by Septembers** [comment]
See issue #100
