### ISSUE TITLE
the variable 'proxy' in Generated PAC script proxy needs to be modified manually, in Windows7

### ISSUE THREAD

**Issue by liuyangcharlie** [shadowsocks/shadowsocks-csharp#195]
I've already add a server in shadowsocks, but when I click 'edit PAC script' in the menu of tray icon:
![win_7](https://cloud.githubusercontent.com/assets/6851070/6681774/5b5143f6-cca7-11e4-97d7-4dae0387f8de.png)
variable proxy is equal to '__PROXY__', which should be set according to the server setting, or shadowsocks should notify user to modify it manually, I spent minutes on finding this problem when I use this script to configure SwitchyOmega
![win_9](https://cloud.githubusercontent.com/assets/6851070/6681777/6930dca2-cca7-11e4-85be-821b48da1d2b.png)
![win_11](https://cloud.githubusercontent.com/assets/6851070/6681799/e45baf92-cca7-11e4-97fe-92eca789b6de.png)
![win_12](https://cloud.githubusercontent.com/assets/6851070/6681801/edbd4636-cca7-11e4-95a5-359be5346399.png)

**Comment by clowwindy** [comment]
The pac.txt file is designed to be used only with Shadowsocks. Actually, the __PROXY__ variable is dynamically determined.

For the SwitchyOmega problem, only the user knows which proxy he want to use. It's his responsibility to set a proper value for the proxy variable. I believe most of people who really need to customize his PAC do know how to set the value.

So I think this isn't a problem of this project. Anyway, thanks for pointing out the problem.

**Comment by liuyangcharlie** [comment]
That's fine. Thanks for your patient explanation.
