### ISSUE TITLE
以pac形式共享代理时，发现对域名的访问会被拒绝

### ISSUE THREAD

**Issue by dangyuluo** [shadowsocks/shadowsocks-csharp#196]
我架设在实验室的服务器上，连接linode没问题，想做一个共享，在宿舍直接以pac的方式用。
遇到的问题是，当我以IP的形式配置pac，形如 http://121.***.175.75:1080/pac?t=201412311720464879
这样访问是正常的，能够正确获取pac。
但是实验室电脑的IP经常变动，因此我配置了个A记录到这个ip上，并配合dnspod动态解析。pac形式形如：http://210.mei***.org:1080/pac?t=201412311720464879。 但是shadowsocks好像不能正确识别，返回的404，我确信解析正确的情况下，应该怎么解决呢？

**Comment by Septembers** [comment]
https://github.com/shadowsocks/shadowsocks-csharp/blob/master/shadowsocks-csharp/Controller/PACServer.cs#L50

**Comment by dangyuluo** [comment]
哈哈，虽然不会c#，但是可以学习学习！

**Comment by Sharuru** [comment]
See issue #189
>No plan for this. You can modify the code yourself or ask a friend to do so.
