### ISSUE TITLE
能不能自定义局域网代理的端口？

### ISSUE THREAD

**Issue by ctexlive** [shadowsocks/shadowsocks-csharp#199]
能不能自定义局域网代理的端口？ 现在默认是8123，不搜索都不知道端口是什么。。。。

**Comment by clowwindy** [comment]
就是你在设置里填的端口

**Comment by ctexlive** [comment]
不对啊。我说不是socks5的本地代理，而是通过ss_polippo提供的http代理端口叫“允许来自局域网的连接“，我找不到在哪里设置。。。

**Comment by clowwindy** [comment]
也是你在设置里填的端口

**Comment by ctexlive** [comment]
非常感谢。我已经搞清楚机制了。原来ss_polipo的8123端口只是提供给shadowsocks-c#程序内部使用的，shadowsocks-c#同时通过服务器设置里定义的本地端口（同一个端口）对外提供socks5和http代理。我一直以为ss_polipo的8123才是对外的http代理端口。。。我去。

**Comment by everyx** [comment]
@ctexlive 最近几个版本的和以前版本的端口规则有些变化，我估计是这个原因导致你出现理解误差的，现在的这种挺好的，比较明白，以前两个居然不一样
