### ISSUE TITLE
能否负载平衡？

### ISSUE THREAD

**Issue by renyouguo** [shadowsocks/shadowsocks-csharp#201]
同时填入多个账号，一个失败了就自动连接另外一个。
也起到节省流量的作用。

**Comment by Septembers** [comment]
cow以实现请使用cow

**Comment by clowwindy** [comment]
No plan for this

**Comment by 02015678** [comment]
@renyouguo 看这个教程(需要科学上网) http://blog.aboutss.tk/2015/02/windowsss.html

**Comment by clowwindy** [comment]
Fixed in 2.5
