### ISSUE TITLE
请教一下PAC模式应该怎么设置呢？

### ISSUE THREAD

**Issue by angel126** [shadowsocks/shadowsocks-csharp#202]
查了下帮助文件都没有找到。。

**Comment by Sharuru** [comment]
在默认状态下，程序默认设定代理模式即为 PAC 模式，在这个模式下你并不需要进行太多的设置，程序会自动设置（你可以在 IE 浏览器中的“自动配置”下观察到设置的变更）并通过程序目录下 `pac.txt` 文件的设定自动侦测你的网络流量，只有文件中存在的地址才会经过代理服务器进行访问。
