### ISSUE TITLE
自定义规则有个问题，不知道是不是C大特意这样做的...

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-csharp#203]
写完自定义规则后要点击 "从 GFWList更新本地PAC" ，自定义规则才生效，之前我发过一个 Issues 问怎么写规则，我还以为是我的规则写错了的问题，原来我的规则没写错.....

**Comment by clowwindy** [comment]
确实会有这个问题，暂时没有想到好的解决办法。

**Comment by Septembers** [comment]
[C#: Application to Watch a File or Directory using FileSystem Watcher](http://www.codeproject.com/Articles/26528/C-Application-to-Watch-a-File-or-Directory-using-F)

**Comment by clowwindy** [comment]
@Septembers 问题不在这里，现在 PAC 本身就是监控的
问题在于本地没有存缓存一份 GFWList，所以 user rule 修改后还是需要重新下一遍 GFWList

**Comment by dofine** [comment]
@LisonFan   原来如此。。难怪我纠结这个自定义规则纠结了好久。。一直不行。。

**Comment by WernerLi** [comment]
原来是这样，我写了很久，以为是自己智商问题就是不生效。。。
