### ISSUE TITLE
强烈要求作者修复这个漏洞

### ISSUE THREAD

**Issue by Leetroch** [shadowsocks/shadowsocks-csharp#204]
在shadowsocks的C#客户端创建的gui-config.json文件下，用户可以轻松地用记事本打开即可查看密码

**Comment by ssc19940105** [comment]
这个不算漏洞吧

**Comment by Leetroch** [comment]
那算什么

2015-03-29 23:22 GMT+08:00 Jenkins CI Bot <notifications@github.com>:

**Comment by Septembers** [comment]
请阅读shadowsocks-csharp源码 谢谢

**Comment by Sharuru** [comment]
关于这个问题，在 issue #155 已经有所解释：
>Safer for what? If you give other people access to your PC, they can just copy your configuration file to their PC. If you don't, why do you need to encrypt a file that only you have access to?

如果你给与了其他人操作你计算机的权限，那么就算文本内的密码是密文保存的，其他人也可以轻易的复制你的配置文件。

**Comment by myliyifei** [comment]
可能他的想法是，不想分享的小白轻易得到SS密码，然后分享给更多的人。

2015-03-30 9:53 GMT+08:00 Sharuru <notifications@github.com>:

**Comment by Leetroch** [comment]
@myliyifei 我就是这个意思
