### ISSUE TITLE
建议同时启动多个服务器

### ISSUE THREAD

**Issue by magic282** [shadowsocks/shadowsocks-csharp#208]
建议同时启动多个服务器。

比如我使用的时候，通常会使用速度较快的DO上的ss做服务器，但是因为DO被Google列入黑名单所以无法访问Google Scholar。我都是使用SwitchyOmega，让Scholar通过搬瓦工上的SS，虽然慢了点。最近看到有这个windows的客户端，所以希望能支持同时启用多个配置，这样免去我同时开两个客户端的麻烦。

**Comment by Sharuru** [comment]
同时启动多个服务器的话，每个服务器的服务端口需要不同指定吧？

**Comment by magic282** [comment]
@Sharuru 是的啊，比如DO的占用1080，搬瓦工的占用1081什么的。

**Comment by Sharuru** [comment]
很抱歉。
多客户端的启动以及多端口的支持暂时没有计划。

issue #194 issue #205

**Comment by magic282** [comment]
好吧_(:з」∠)_

**Comment by 02015678** [comment]
@magic282 看这个教程(需要科学上网) http://blog.aboutss.tk/2015/02/windowsss.html
