### ISSUE TITLE
Win8 Modern App访问代理失败

### ISSUE THREAD

**Issue by troismph** [shadowsocks/shadowsocks-csharp#210]
现象：Win8桌面应用正常访问shadowsocks在本地建立的代理，但Modern UI App无法访问，IE显示127.0.0.1:XXXX 端口上的代理服务器没有响应。换过端口，都无法正常工作。

环境：Windows 8.1 Pro, x64, 安装了2015年4月7日前所有更新。在我的两台机器上都有此现象，一台联想的台式机，一台笔记本。

**Comment by Sharuru** [comment]
你好，尝试过使用诸如 Proxifier 等软件进行全局代理设置进行访问么？

Metro App 无法使用代理有可能和微软的设定有关，以下这些链接有可能帮到你：

How to setup a proxy for Modern UI (aka Metro) Apps in Windows 8?
http://superuser.com/questions/397577/how-to-setup-a-proxy-for-modern-ui-aka-metro-apps-in-windows-8

How to Set Proxy For Metro Apps in Windows 8
http://www.c-sharpcorner.com/UploadFile/7e39ca/how-to-configure-proxy-for-metro-apps-in-windows-8/

**Comment by troismph** [comment]
谢谢，根据你提供的链接，找到了问题所在：Win8 Modern App默认是无权访问loopback地址的，而shadowsocks客户端把代理开在了127.0.0.1上。下载了工具打开App的访问权限即可。

下载链接在此，页面中搜索"loopback"即可：
http://www.telerik.com/fiddler/add-ons
