### ISSUE TITLE
能否考虑添加一个基于域名的广告过滤列表？

### ISSUE THREAD

**Issue by gonejack** [shadowsocks/shadowsocks-csharp#213]
主要用于过滤一些广告联盟的广告，稍微改写一下PAC规则判定，应该不会太麻烦作者，ABP插件太拖Chrome了。

**Comment by Sharuru** [comment]
在现时，过滤广告已经有很多不同的选择，ABP 不喜欢用的话可以考虑使用 μBlock，不喜欢使用插件的话可以使用本地的软件，比如 ADSafe，广告屏蔽大师等等。如果你的网络硬件支持，你甚至可以直接在路由器中进行广告的过滤。

为何要让一个软件做一个和她设计初衷根本不同的事情？仅仅是因为 Shadowsocks-Csharp 管理了网络还是因为她支持 PAC？

既然认为不麻烦作者，为何你不自己来试试看呢？

**Comment by CNMan** [comment]
goagent的pac有这个
https://github.com/goagent/goagent/blob/3.0/local/proxy.pac

**Comment by gonejack** [comment]
多谢，开始试着改写下，判断为广告域名要返回什么值好呢？
