### ISSUE TITLE
关于系统代理模式的切换。

### ISSUE THREAD

**Issue by euisk** [shadowsocks/shadowsocks-csharp#214]
两个问题：
1、当第一次点击了启用 系统代理 后即使关闭该选项代理功能依然没有被关闭。

2、pac模式与全局模式并不能随时进行切换，当更改代理模式后需要重启shadowsocks。

想知道这两个问题属于我个人问题还是程序问题。

一个建议：
建议在显示二维码界面增加一个保存二维码图片按钮方便分享。

**Comment by Sharuru** [comment]
你好，关于问题一的开关功能，其控制的只是 PAC 文件的生效与否（你可以通过查看 Internet 的代理设置发现配置的变动），SOCKS 代理目前暂时没有独立的开关去控制。
至于问题二的全局模式与 PAC 模式的切换问题，我在 2.3.1 版本中进行了测试（测试方法：分别切换模式后使用百度查看自己的 IP），认为这个功能是正常的。这有可能是你个人的问题，请尝试更新一下版本。

请注意：模式切换时由于服务器响应速度的问题，可能会存在一定的延迟。

**Comment by xdl122570** [comment]
遇到同样的问题 系统是win7 x64
任务栏图标右键的 启用系统代理 点击没有效果 在 Internet代理设置里的配置没有变化
要退出重新打开软件 Internet代理设置才有变化 
关闭的时候需在Internet代理设置里关闭 通过任务栏右键无法关闭


另外任务栏图标右键的系统代理模式里的pac模式与全局模式不能随时进行切换
点击切换模式后要重新启动软件模式才能切换过去

**Comment by Sharuru** [comment]
你好，我的环境是 Windows 8.1 x64，在测试时候没有发现这个问题。

关于这个代理开关以及全局、PAC 模式的切换问题，我分别在一台 Windows 7 x32 以及安装在虚拟机中的 Windows 7 x64 进行了测试，发现确实存在这个问题。
我也拓展了一下这个测试，在 Windows XP x32 中，这个问题没有发生。

我查看了一下 [/Controller/SystemProxy.cs](https://github.com/shadowsocks/shadowsocks-csharp/blob/master/shadowsocks-csharp/Controller/SystemProxy.cs#L29-L78) 的代码，认为逻辑上并没有错误。有可能是 UI 方面等其他方面的问题。

不知诸位可否在更多的机器上进行下测试，以确定这个案例只在 Windows 7 中发生？

**Comment by xdl122570** [comment]
我用同学电脑试了下 同样出现这个问题 也是win7 x64

Sharuru <notifications@github.com>于2015年4月22日星期三写道：
> 你好，我的环境是 Windows 8.1 x64，在测试时候没有发现这个问题。
>
> 关于这个代理开关以及全局、PAC 模式的切换问题，我分别在一台 Windows 7 x32 以及安装在虚拟机中的 Windows 7 x64
进行了测试，发现确实存在这个问题。
> 我也拓展了一下这个测试，在 Windows XP x32 中，这个问题没有发生。
>
> 我查看了一下 /Controller/SystemProxy.cs 的代码，认为逻辑上并没有错误。有可能是 UI 方面等其他方面的问题。
>
> 不知诸位可否在更多的机器上进行下测试，以确定这个案例只在 Windows 7 中发生？
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/wzbhBT7re0Ko8vNXnO9FMBGdWEH3llxk2gHtE4TbcxBXsJAMOzBOv_VdByAf-l2MJqAaY1qYLlpFnG_Wns8mI1BSU7mTgqfkRFlqO216dU4YefVZZXAiHAfodvFQSrUXmlpd34Jqu1EkyrN4m9Ra0N70CoIkIQ=s0-d-e1-ft#https://github.com/notifications/beacon/ALfH9gK2duA3xXssBbkYC1Tz-IvayUv4ks5oBvL9gaJpZM4ED88L.gif
>

**Comment by minoscc** [comment]
v2.3.1 OS win7 x64 下administrator使用正常~~

**Comment by euisk** [comment]
Shadowsocks 2.3.1
windows 7 x64 IE8 环境下会出现这个问题，我尝试更新到IE11，发现这个问题消失了。
估计跟IE版本过低有关。

**Comment by xdl122570** [comment]
确实 原先是IE8 更新到IE11后就问题就解决了

**Comment by Sharuru** [comment]
感谢诸位提供信息。
[NotifyIE](https://github.com/shadowsocks/shadowsocks-csharp/blob/master/shadowsocks-csharp/Controller/SystemProxy.cs#L15-L27) 就是为了实现更改设置后通知 IE 的功能，不过没想到在 Windows 7 with IE 8 的时候表现不够好。
奇怪的是 Windows XP with IE 8 时却工作正常。
