### ISSUE TITLE
内存、CPU用量异常

### ISSUE THREAD

**Issue by gy199445** [shadowsocks/shadowsocks-csharp#225]
系统环境 windows7 64位旗舰版
软件版本 2.3.1
几周前是正常的，内存占用不到10MB，CPU占用为0。最近突然出了问题，一启动shadowsocks-gui，该进程内存占用就高达700MB，如果不关闭的话还会继续增长，CPU50%以上，软件没有任何报错。

**Comment by clowwindy** [comment]
能否提供截图和 log？

**Comment by gy199445** [comment]
[2015-07-09 18:53:01] Shadowsocks started
[2015-07-09 18:53:24] System.Net.Sockets.SocketException: 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.PortForwarder.Handler.Start(Byte[] firstPacket, Int32 length, Socket socket, Int32 targetPort)
截图：https://lh5.googleusercontent.com/-AFIH2jfA3Fk/VZ5UoAPK5oI/AAAAAAAASHM/KUxMVPUkR0o/w586-h48-no/shadowsockslog.PNG

**Comment by chenshaoju** [comment]
这个问题可能和你的Windows Winsocks有关。
以管理员权限运行命令提示符，然后执行：
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
一行一个，三个指令执行完毕后，重新启动计算机，再观察一下。

**Comment by gy199445** [comment]
chenshaoju的方法试过了，问题依然，log也一样。
另外，shadowsocks-qt5和命令行客户端均可以正常运行。

**Comment by GangZhuo** [comment]
试试 http://www.cyqdata.com/cyq1162/article-detail-54385

**Comment by chenshaoju** [comment]
@GangZhuo 我猜测和这个无关。

@gy199445 这个诡异的问题我也在一台Windows 2008的服务器上遇到过，和Shadowsocks没有关系（是敝司的一个私有软件），一直解决不了，只能重装系统。后来，怀疑和 .NET Framework运行时环境有关。

你试试这个，彻底清除 .NET Framework，然后重新安装：
https://www.microsoft.com/en-us/download/details.aspx?id=30135

**Comment by GangZhuo** [comment]
@chenshaoju  具体我不知道了。我分析的原因可能是使用 HTTP 代理的时候，有大量的 Keep-Alive 请求 导致连接数超过系统允许的最大连接数量导致的。具体浏览器是如何处理 Keep-Alive 我不清楚了。仅供参考。

**Comment by clowwindy** [comment]
设置的代理端口是？

**Comment by chenshaoju** [comment]
@GangZhuo 我非常想知道他出现问题的时候到底是什么导致内存占用如此巨大，要是有条件，想用VMMap观察一下。 https://technet.microsoft.com/en-us/library/dd535533.aspx

**Comment by gy199445** [comment]
@clowwindy  8123

**Comment by clowwindy** [comment]
换一个，8123 会导致循环代理给自己。

**Comment by clowwindy** [comment]
加上了检查，防止设置此端口。
https://github.com/shadowsocks/shadowsocks-csharp/commit/f9f49552aeb0403c69cb6deb8cd9d3dc6a5a98aa
