### ISSUE TITLE
能不能加个测试IP的功能

### ISSUE THREAD

**Issue by Sartner** [shadowsocks/shadowsocks-csharp#230]
能不能加个测试IP的功能..
有多个ss服务器,  经常挂掉不能用,.
然后又要再列表里一个一个试,哪个是好的

**Comment by clowwindy** [comment]
可以尝试这个版本
https://github.com/TkYu/shadowsocks-csharp-withping

如果反响好未来可能会合到主线

**Comment by septs** [comment]
我认为这是个常见问题可以补充到**README**

**Comment by Jingler** [comment]
认为没有必要。
