### ISSUE TITLE
Combine headers

### ISSUE THREAD

**Issue by clowwindy** [shadowsocks/shadowsocks-csharp#95]

**Comment by douglas-lee** [comment]
Windows 2.2版本，从gfwlist更新了pac后就打不开翻墙网站了。删除掉，用默认的pac就正常。

**Comment by Septembers** [comment]
What is "Combine Headers"?

**Comment by clowwindy** [comment]
Combine Shadowsocks header with first packet from user data. Currently only Python sslocal supports this.
